# Site settings
title: Banco de conhecimento
email: masptj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um pequeno banco de informações sobre tudo o que preciso para minhas atividades.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://masptj.github.io" # the base hostname & protocol for your site
twitter_username: masptj
github_username:  masptj

# Build settings
markdown: kramdown
